### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by blahdy** [alau/dotfiles#1]
Hello. I have trouble finding DKP LogParser 1.4.1c for windows, since your site is down. Is there any chance you can share a link for it if you have it left?

Sorry to communicate in such a manner, but this is the only way found to. =0)

Would really appreciate it. Thanks!

**Comment by alau** [comment]
Hello there,
I can take a look during the week and see if I can find a copy. If it's of any use, there is a copy of `1.3.10f` at http://lokorin.org/_downloads/dkp-log-parser-win32-1-3-10f.zip .

**Comment by blahdy** [comment]
I'd be really grateful if you did. We already found 1.4.0f, but he's really eager to have the last. Should I remind you to have a look? And do you per chance have Telegram? Issue tracker seems not the place to ask. =0)

**Comment by alau** [comment]
Feel free to remind me if I have not responded during the coming week. I do not have Telegram, but using the issue tracker is fine with me.

**Comment by alau** [comment]
Here it is: http://lokorin.org/_downloads/dkp-log-parser-1.4.1c-win32.zip

**Comment by blahdy** [comment]
Thanks, Andreas!
